config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  
  resources :posts

  get 'latest', to: 'posts#latest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :slug, :datetime, :published, :comments_enabled, presence: true
    validates :slug, uniqueness: true

    has_rich_text :body
    has_one_attached :hero_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show, :latest]
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.all
    end

    def new
        @form_title = "New Post"
        
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to "/posts/#{@post.slug}"
        else
            # flash.now[:error] = error_message
            render :new
        end
    end

    def update
        if @post.update(post_params)
            redirect_to "/posts/#{@post.slug}"
        else
            # flash.now[:error] = error_message
            render :edit
        end
    end

    def edit
        @form_title = "Edit Post"
    end

    def show
    end

    def destroy
        @post.destroy

        redirect_to posts_path
    end

    def latest
        @post = Post.order(created_at: :desc).first
        redirect_to action: "show", id: @post.slug
    end

    private

    def post_params
        params.require(:post).permit(:title, :slug, :subtitle, :datetime, :hero_image, :body, :published, :comments_enabled)
    end

    def set_post
        @post = Post.find_by_slug(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_header.html.erb
<nav aria-label="main navigation" class="navbar" role="navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="<%= root_url %>">
            <img alt="logo" src="https://bulma.io/images/bulma-logo.png">
        </a>
        <a aria-expanded="false" aria-label="menu" class="navbar-burger burger" id="navbar-burger" roles="button">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div class="navbar-menu" id="mobile-navbar">
        <div class="navbar-start">
            <a class="navbar-item" href="<%= posts_path %>">Posts</a>
            <a class="navbar-item" href="/latest">Latest</a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link" href="/contact">Contact</a>

                <div class="navbar-dropdown">
                    <a class="navbar-item" href="/about">
                        <span class="icon">
                            <%= fa_icon "user-circle" %>
                        </span>
                        <span>About</span>
                    </a>
                    <a class="navbar-item" href="/portfolio">
                        <span class="icon">
                            <%= fa_icon "briefcase" %>
                        </span>
                        <span>Portfolio</span>
                    </a>
                    <a class="navbar-item" href="/hire-me">
                        <span class="icon">
                            <%= fa_icon "thumbs-up" %>
                        </span>
                        <span>Hire Me!</span>
                    </a>
                    
                    <hr class="navbar-divider">

                    <a class="navbar-item" href="/bugs">
                        <span class="icon">
                            <%= fa_icon "bug" %>
                        </span>
                        <span>Report an issue</span>
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <% if user_signed_in? %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        <span class="icon">
                            <%= fa_icon "user-circle" %>
                        </span>
                        <span><%= current_user.email %></span>
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            <span class="icon">
                                <%= fa_icon "sliders" %>
                            </span>
                            <span>Settings</span>
                        </a>
                        <a class="navbar-item">
                            <span class="icon">
                                <%= fa_icon "comments" %>
                            </span>
                            <span>Comments</span>
                        </a>

                        <% if current_user.role == "admin" %>
                            <a class="navbar-item" href="<%= new_post_url %>">
                                <span class="icon">
                                    <%= fa_icon "plus-circle" %>
                                </span>
                                <span>New Post</span>
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item">
                                <span class="icon">
                                    <%= fa_icon "users" %>
                                </span>
                                <span>Users</span>
                            </a>
                            <a class="navbar-item">
                                <span class="icon">
                                    <%= fa_icon "bar-chart" %>
                                </span>
                                <span>Stats</span>
                            </a>
                        <% end %>

                        <hr class="navbar-divider">
                        <%= link_to destroy_user_session_url, method: :delete, class: "navbar-item" do %>
                            <span class="icon">
                                <%= fa_icon "sign-out" %>
                            </span>
                            <span>Log out</span>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="<%= new_user_registration_url %>">
                            <strong>Sign up</strong>
                            <span class="icon">
                                <%= fa_icon "user-plus" %>
                            </span>
                        </a>
                        <a class="button is-light" href="<%= new_user_session_url %>">
                            <strong>Log in</strong>
                            <span class="icon">
                                <%= fa_icon "sign-in" %>
                            </span>
                        </a>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_comments.html.erb
<div class="container is-max-desktop is-max-post my-6 box">
    <h1 class="title">Comments</h1>
    <div class="has-text-centered mt-6">
        <button class="button is-info" id="load-comments">
            <span>Load Comments</span>
            <span class="icon">
                <%= fa_icon "comments" %>
            </span>
        </button>
    </div>
    <div id="disqus_thread">
    </div>
    
    <script>
        const loadCommentsBtn = document.getElementById('load-comments');
        loadCommentsBtn.addEventListener('click', loadComments, false);

        const disqus_config = function() {
            this.page.url = 'http://localhost:3000';
            this.page.identifier = 'slug';
        };

        const disqus_shortname = 'jwdonovan-blog';
        
        function loadComments() {
            (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();

            loadCommentsBtn.remove();
        }
    </script>
</div>

app/views/posts/_comments_disabled.html.erb
<div class="container box is-max-desktop is-max-post has-text-centered my-6">Comments have been disabled</div>

app/views/posts/_form.html.erb
<!--
title
slug
subtitle
datetime
hero image
body
published
comments_enabled
-->

<%= form_with model: @post, class: "container is-max-desktop is-max-post mt-6" do |f| %>
    <h1 class="title"><%= @form_title %></h1>

    <%= f.text_field :title, placeholder: "Title", class: "input mb-4", id: "post-title", autocomplete: "off" %>
    <%= f.text_field :slug, placeholder: "Slug", class: "input mb-4", id: "post-slug" %>
    <%= f.text_field :subtitle, placeholder: "Subtitle", class: "input mb-4" %>
    <%= f.datetime_local_field :datetime, class: "input mb-4" %>
    <div class="file has-name is-fullwidth mb-4">
        <label class="file-label">
            <%= f.file_field :hero_image, class: "file-input" %>
            <span class="file-cta">
                <span class="file-icon">
                    <%= fa_icon "upload" %>
                </span>
                <span class="file-label">
                    Choose a hero image...
                </span>
            </span>
            <span class="file-name"></span>
        </label>
    </div>
    <%= f.rich_text_area :body, class: "editor-min-height mb-4" %>
    <label class="checkbox mb-4">Publish<%= f.check_box :published, class: "ml-2" %></label>
    <label class="checkbox mb-4 ml-4">Enable Comments<%= f.check_box :comments_enabled, class: "ml-2" %></label>
    <div class="is-grouped">
        <a class="button is-danger is-outlined" href="<%= posts_url %>">
            <span>Discard</span>
            <span class="icon is-small">
                <%= fa_icon "times" %>
            </span>
        </a>
        <button class="button is-success" type="submit">
            <span>Save</span>
            <span class="icon is-small">
                <%= fa_icon "check" %>
            </span>
        </button>
    </div>
<% end %>

<!-- redirect to show using slug on save, show error on missing params, required fields, add padding/styling to trix editor -->

app/views/posts/edit.html.erb
<%= render partial: 'application/header' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render partial: 'application/header' %>

<section class="container is-max-desktop is-max-post">
    <% @posts.each do |p| %>
        <div class="box content mt-6">
            <a href="<%= post_path(p.slug) %>">
                <h1 class="title is-2"><%= p.title %></h1>
            </a>
            <p class="subtitle is-italic is-4"><%= p.subtitle %></p>
            <%= time_ago_in_words(p.datetime) + ' ago' %>
            <div class="content my-4" style="max-height: 10em; text-overflow: ellipsis; overflow: hidden;"><%= p.body %></div>
            <a class="button is-light is-primary" href="<%= post_path(p.slug) %>">
                <span class="mr-2">Read</span>
                <%= fa_icon "book" %>
            </a>

            <% if user_signed_in? && current_user.role == "admin" %>
                <a class="button is-light is-link" href="<%= edit_post_path(p.slug) %>">
                    <span class="mr-2">Edit</span>
                    <%= fa_icon "pencil" %>
                </a>
                <%= link_to post_path(p.slug), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger is-light" do %>
                    <span class="mr-2">Delete</span>
                    <%= fa_icon "trash" %>
                <% end %>
            <% end %>
        </div>
    <% end %>
</section>

app/views/posts/new.html.erb
<%= render partial: 'application/header' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render partial: 'application/header' %>

<section class="container is-max-desktop is-max-post mt-6 p-6">
    <h1 class="title pb-2 is-size-4-touch"><%= @post.title %></h1>
    <p class="mb-2 is-italic has-text-weight-light has-text-grey-dark"><%= @post.subtitle %></p>
    <!--<%= @post.datetime %>-->
    <%= time_ago_in_words(@post.datetime) + ' ago' %>
    <figure class="image">
        <%= image_tag(@post.hero_image) %>
    </figure>
    <div class="content my-6">
        <%= @post.body %>
    </div>
    <!--<%= @post.published %>-->
    <% if @post.comments_enabled %>
        <%= render partial: 'posts/comments' %>
    <% else %>
        <%= render partial: 'posts/comments_disabled' %>
    <% end %>
</div>